web: uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 4 --loop uvloop --http httptools --proxy-headers --forwarded-allow-ips *
worker: celery -A app.celery_app:celery_app worker --loglevel=INFO --concurrency=4
beat: celery -A app.celery_app:celery_app beat --loglevel=INFO
